---
- name: Ensure group "sudo" exists
  group:
    name: sudo
    state: present

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: Create main_user
  user:
    name: "{{ main_user_USERNAME | default('user') }}"
    uid: "{{ main_user_UID | default('1050') }}"
    append: yes
    password: "{{ main_user_PASSWORD | password_hash('sha512') }}"
    groups: docker, sudo

- name: Setup sudoers for %sudo all nopasswd
  lineinfile:
    path: /etc/sudoers
    line: "%sudo  ALL=(ALL)       NOPASSWD: ALL"
    regexp: "\\%sudo\\s+"
    create: yes