---
- name: Install zsh Fedora
  include_tasks: fedora_install_zsh.yml
  when: ansible_distribution == "Fedora"

- name: Install Oh-My-Zsh
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh"
    dest: "~/.oh-my-zsh"
  become: yes
  become_user: "{{ main_user_USERNAME | default('user') }}"

- name: Clone the zsh-theme
  git:
    repo: "https://github.com/denysdovhan/spaceship-prompt.git"
    dest: "/home/{{ main_user_USERNAME | default('user') }}/.oh-my-zsh/custom/themes/spaceship-prompt"
  become: yes
  become_user: "{{ main_user_USERNAME | default('user') }}"

- name: Link the theme into ZSH_CUSTOM directory
  file:
    src: "/home/{{ main_user_USERNAME | default('user') }}/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme"
    dest: "/home/{{ main_user_USERNAME | default('user') }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
    state: link

- name: Copy the zshrc
  template:
    src: zshrc
    dest: "/home/{{ main_user_USERNAME | default('user') }}/.zshrc"

- name: Ensure user exist and has zsh as shell
  user:
    name: "{{ main_user_USERNAME | default('user') }}"
    shell: "/usr/bin/zsh"
