version: '3'
services:

  nginx:
    image: jwilder/nginx-proxy:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    volumes:
      - "${DATA_FOLDER}/nginx/conf.d:/etc/nginx/conf.d"
      - "${DATA_FOLDER}/nginx/vhost.d:/etc/nginx/vhost.d"
      - "${DATA_FOLDER}/nginx/certs/:/etc/nginx/certs/:ro"
      - "${DATA_FOLDER}/nginx/html:/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

  nginxletsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: nginxletsencrypt
    restart: unless-stopped
    environment:
      - "NGINX_PROXY_CONTAINER=nginx"
    volumes:
      - "${DATA_FOLDER}/nginx/conf.d:/etc/nginx/conf.d"
      - "${DATA_FOLDER}/nginx/vhost.d:/etc/nginx/vhost.d"
      - "${DATA_FOLDER}/nginx/certs:/etc/nginx/certs"
      - "${DATA_FOLDER}/nginx/html:/usr/share/nginx/html"
      - "${DATA_FOLDER}/nginx/htpasswd:/etc/nginx/htpasswd:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    
  watchtower:
    image: v2tec/watchtower:latest
    restart: unless-stopped
    container_name: watchtower
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  portainer:
    image: portainer/portainer:latest
    restart: unless-stopped
    container_name: portainer
    environment:
      - "VIRTUAL_HOST=portainer.${BASE_DOMAIN}"
      - "VIRTUAL_PORT=9000"
      - "LETSENCRYPT_HOST=portainer.${BASE_DOMAIN}"
      - "LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}"
    ports:
      - "9000:9000"
    volumes:
      - "${DATA_FOLDER}/portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"

  netdata:
    image: titpetric/netdata:latest
    restart: unless-stopped
    container_name: netdata
    environment:
      - "VIRTUAL_HOST=netdata.${BASE_DOMAIN}"
      - "VIRTUAL_PORT=19999"
      - "LETSENCRYPT_HOST=netdata.${BASE_DOMAIN}"
      - "LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
    - SYS_PTRACE
