---
- name: Install dnf-plugins-core
  dnf:
    name: dnf-plugins-core
    update_cache: yes
    state: latest

- name: Add docker-ce repo
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  args:
    warn: false
  when: ansible_distribution == "Fedora"

- name: Install docker packages
  dnf:
    name: docker-ce, docker-ce-cli, containerd.io
    update_cache: yes
    state: latest
  when: ansible_distribution == "Fedora"
