---
- name: Download helm 2.16.1 in /tmp
  get_url:
    url: "https://get.helm.sh/helm-v2.16.1-linux-amd64.tar.gz"
    dest: "/tmp/helm-v2.16.1-linux-amd64.tar.gz"
    follow: yes
    mode: "644"

- name: create helm 2 directory
  file:
    path: "/opt/helm/2"
    state: directory

- name: Extract helm 2 in /opt/helm/2
  command: tar xzf /tmp/helm-v2.16.1-linux-amd64.tar.gz -C /opt/helm/2/ --strip 1
  args:
    warn: false

- name: Remove the downloaded archive in /tmp
  file:
    path: /tmp/helm-v2.16.1-linux-amd64.tar.gz
    state: absent

- name: install helm version 2
  alternatives:
    link: /opt/bin/helm
    name: helm
    path: /opt/helm/2/helm

- name: install associated binary tiller version 2
  alternatives:
    link: /opt/bin/tiller
    name: tiller
    path: /opt/helm/2/tiller
