#!/bin/bash

function main {
  ansible-playbook --version &> /dev/null
  if [ $? -ne 0 ]; then
    install_ansible
  fi

  ansible-playbook ./books/$1.yml -i hosts --vault-password-file ./.vault_pass
}

function install_ansible {
  # Work on debian 10 untested on other distros
  LINUX_VERSION=$(cat /etc/os-release | grep -e "^ID=" | cut -d= -f 2)
  case $LINUX_VERSION in
    "debian")
      install_ansible_debian
      ;;
  esac
}

function install_ansible_debian {
  ANSIBLE_REPO="deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main"
  if ! grep "$ANSIBLE_REPO" /etc/apt/sources.list ; then
    echo -e "\n#Ansible Repos\n$ANSIBLE_REPO" | sudo tee -a /etc/apt/sources.list
  fi
  sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
  sudo apt update
  sudo apt install ansible
}

main $@
