- hosts: Aiba
  remote_user: root
  roles:
   - common
   - desktop/lightdm
   - desktop/awesomewm
   - apps/git
   - apps/neovim
   - apps/nodejs
   - apps/fish
   - services/tigervnc
   - services/novnc
   - platforms/docker_host
   - apps/python
   - apps/google-chrome
   - apps/rofi
   - apps/kitty
   - "apps/aws-cli"
   - role: common/dotconfig
     application: vim
   - role: common/dotconfig
     application: kitty
   - role: common/dotconfig
     application: fish
   - role: common/dotconfig
     application: awesomewm
  vars:
    user: lucas
  vars_files:
    - ../group_vars/vault
