- hosts: WSL
  remote_user: root
  roles:
    - common
    - apps/git
    - role: apps/zsh
      chsh: yes
    - apps/oh-my-zsh
    - role: apps/neovim
      extracted: True
    - apps/nodejs
    - apps/python
    - platforms/docker_host
    - apps/aws-cli
    - apps/zoxide
    - apps/bat
    - apps/fzf
    - apps/ripgrep
    - apps/lazygit
    - role: common/dotconfig
      application: vim
    - role: common/dotconfig
      application: zsh
  vars:
    user: lucas
  vars_files:
    - ../group_vars/vault
