---
- name: Install Oh my fish
  shell: |
    curl -L github.com/oh-my-fish/oh-my-fish/raw/master/bin/install > install
    ./install --noninteractive
    rm ./install
  args:
    warn: no
  become: yes
  become_user: '{{ user }}'