---
- name: Install zsh
  include_role:
    name: utils/simple_package_install
  vars:
    package: zsh

- name: Change {{ user }} default shell
  become: yes
  user:
    name: "{{ user }}"
    shell: /bin/zsh
  when: chsh|bool == True
