---
- name: Install add-apt-repository
  apt:
    name: apt-transport-https, ca-certificates, curl, gnupg2, software-properties-common
    update_cache: yes
    state: latest

- name: Add docker-ce gpg
  shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
  args:
    warn: false

- name: Add docker-ce repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
  args:
    warn: false

- name: Install docker packages
  apt:
    name: docker-ce, docker-ce-cli, containerd.io
    update_cache: yes
    state: latest
