---
- name: Install dotfiles
  shell: "stow -t $HOME {{ application }}"
  args:
    chdir: "/home/{{ user }}/Workspace/github.com/lucasfabre/Dotfiles/"
    warn: no
  ignore_errors: yes
  become: yes
  become_user: '{{ user }}'
  failed_when: False
