# simulate bash path
export PATH=$HOME/bin:/usr/local/bin:$PATH

# user path
export PATH=$HOME/.bin:$PATH

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="spaceship"

plugins=(
  git
  sudo
)

source $ZSH/oh-my-zsh.sh

# User configuration

export EDITOR='vim'
