---
- name: Populate service facts
  service_facts:

- name: Stop drivemount service
  service:
    name: drivemount
    state: stoped
  when: "'drivemount' in services"

- name: Create gdrive rclone service
  copy:
    src: drivemount.service
    dest: /etc/systemd/system/drivemount.service

- name: Start drivemount service
  service:
    name: drivemount
    state: started
    daemon_reload: yes
    enabled: yes
